### PR TITLE
Remove `sort(::Dict)` piracy (as bugfix)

### LINKED ISSUE #25: Type piracy?
We're having an issue using Julia from the Juno REPL (which imports `OrderedCollections`), in which `sort()` of a `Dict` returns an `OrderedDict` even though the user didn't import `OrderedCollections`.  The unexpected behavior is described here:

https://discourse.julialang.org/t/juno-repl-behaves-differently-than-terminal-repl/29469/2

The culprit appears to be :
```julia
julia> d = Dict(1 => "a", 3 => "b", 0 => "c")
Dict{Int64,String} with 3 entries:
  0 => "c"
  3 => "b"
  1 => "a"

julia> sort(d)
OrderedCollections.OrderedDict{Int64,String} with 3 entries:
  0 => "c"
  1 => "a"
  3 => "b"

julia> @which sort(d)
sort(d::Dict) in OrderedCollections at /Users/dpo/.julia/packages/OrderedCollections/E21Rb/src/dict_sorting.jl:21
```
Thanks.

### PR DESCRIPTION
**Pull request by ericphanson**
Fixes #25 

Alternative to #109 - if PkgEval says none of our direct dependents are relying on this deprecated pathway, perhaps we can remove the sort deprecation as a bugfix. (Suggested by @KristofferC).

@maleadt would it be possible to enable nanosoldier on this repo? (per https://github.com/JuliaCI/Nanosoldier.jl#reverse-ci-for-packages).

### CODE REVIEW

**Comment by ericphanson** [comment]
Let us try it:

@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaCollections/OrderedCollections.jl@f07867e vs. JuliaCollections/OrderedCollections.jl@c3687a8: Accepted

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaCollections/OrderedCollections.jl@f07867e vs. JuliaCollections/OrderedCollections.jl@c3687a8: Running

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaCollections/OrderedCollections.jl/pull/110#issuecomment-1821704814) failed. Consult the server logs for more details (cc @maleadt).

**Comment by maleadt** [comment]
I've deployed some fixes.

@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaCollections/OrderedCollections.jl@f07867e vs. JuliaCollections/OrderedCollections.jl@c3687a8: Accepted

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaCollections/OrderedCollections.jl@f07867e vs. JuliaCollections/OrderedCollections.jl@c3687a8: Running

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaCollections/OrderedCollections.jl/pull/110#issuecomment-1823492407) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f07867e_vs_c3687a8/report.html) is available.

**Comment by ericphanson** [comment]
I’m assuming the timeouts are unrelated, but the two failures are both real. Interestingly the OPFSampler one hits a Compat.jl method with this PR due to https://github.com/JuliaLang/Compat.jl/pull/804

**Comment by maleadt** [comment]
Lots of timeouts though... I've added some debugging code to see what's going on. Hopefully you don't mind me using this PR to debug PkgEval; feel free to remove those comments afterwards 🙂 

@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaCollections/OrderedCollections.jl@f07867e vs. JuliaCollections/OrderedCollections.jl@c3687a8: Accepted

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaCollections/OrderedCollections.jl@f07867e vs. JuliaCollections/OrderedCollections.jl@c3687a8: Running

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaCollections/OrderedCollections.jl/pull/110#issuecomment-1824463359) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f07867e_vs_c3687a8/report.html) is available.

**Comment by KristofferC** [comment]
Looks ok to me, the failure in https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f07867e_vs_c3687a8/OPFSampler.primary.log is not a failure in the package itself but a failure that only occurs from the testing code (which has a trivial fix).

**Comment by ericphanson** [comment]
Shall we do DataStructures dependents too, as it reexports OrderedCollections api? I guess I’d need to pass them all in a long list to nanosoldier

**Comment by ericphanson** [comment]
Let us try DataStructures deps:

@nanosoldier `runtests(["MatrixCompletion", "AvailablePotentialEnergyFramework", "CircoCore", "Jusdl", "CJKFrequencies", "Coluna", "QuantumCircuitOpt", "OMJulia", "Sched", "YasolSolver", "CurricularAnalytics", "Finch", "UnfoldMakie", "FiniteStateTransducers", "Polyomino", "MotifPvalue", "ODEInterfaceDiffEq", "StatsPlots", "StorageSystemsSimulations", "ValueHistories", "KongYiji", "MahjongTiles", "ModalDecisionTrees", "ARCHModels", "InvariantCausal", "Dolang", "ObjectOriented", "Discretizers", "TinyModia", "MultilayerGraphs", "BKTrees", "Santiago", "PSID", "PrincipalMomentAnalysisApp", "GIFImages", "PhyloNetworks", "Signals", "SegmentIntersections", "TraceEstimators", "IceFloeTracker", "Scruff", "Sisyphus", "TenPuzzle", "UnitRangesSortedSets", "Ignite", "Backtester", "StructC14N", "MriResearchTools", "LightBSON", "NeutralLandscapes", "DSGE", "IntegratedOscillatorModel", "GeneralizedGenerated", "ServerMetrics", "Omega", "Phylo", "ReactiveMP", "MIPLearn", "QXTns", "TiffImages", "Caching", "Pandoc", "Turing", "ADRIA", "AudioSchedules", "MusicManipulations", "ObjectPools", "ExprOptimization", "PPTX", "NearestNeighborDescent", "Gnuplot", "LabMaze", "DBnomics", "STAC", "PkgCite", "GenieBuiltLifeProto", "JsonGrinder", "DIVAnd", "TabletWeaving", "TimetableSolver", "StochasticIntegrals", "StringAnalysis", "DelaunayTriangulation", "GeoArrayOps", "PhaseSpaceIO", "ClimaCore", "Transformers", "Checkpoints", "DelaySSAToolkit", "SaguaroTrader", "Metrics", "OptimizedEinsum", "Molly", "Gridap", "DiscreteEventsLite", "RCall", "PolyJuMP", "EBIC", "OMETIFF", "SegmentAnalytics", "CSetAutomorphisms", "StaticWebPages", "CryoGrid", "Bibliography", "Decapodes", "Impostor", "K8sClusterManagers", "ImageComponentAnalysis", "Rocket", "Compose", "ZigZagBoomerang", "RRRMC", "QMDDocTools", "InfiniteOpt", "AsyPlots", "SpmGrids", "SpmSpectroscopy", "Luxor", "ReinforcementLearningTrajectories", "InfrastructureSystems", "FastRunningMedian", "WavePropBase", "PowerAnalytics", "Taylor", "Zarr", "StatProfilerHTML", "PowerGraphics", "UnitCommitment", "Catalyst", "Visor", "SpmImages", "Lerche", "SimString", "HetaSimulator", "Dagger", "ClusterRunner", "StructuralIdentifiability", "BokehServer", "GraphKernels", "Air", "FlashWeave", "SymmetricPolynomials", "Sundials", "SpinMonteCarlo", "TimeDag", "Dagitty", "Checkpointing", "Amaru", "GeometricFlux", "RegressionAndOtherStories", "BSONify", "DoubleEnded", "PyDSTool", "AStarSearch", "JuliaFormatter", "Pigeons", "ICD_GEMs", "PolynomialMatrices", "KeldyshED", "MLSuite", "Manopt", "Qwind", "TextParse", "DFTforge", "SimplePlots", "Mimi", "Graphs", "OptimalMatrixCompletion", "StatsBase", "ResourcePools", "Crispulator", "CDCLsat", "Eikonal", "SpinAdaptedSecondQuantization", "TeaFiles", "Scheduling", "HerbGrammar", "ALFA", "Sunny", "AlphaZero", "Classes", "Boscia", "MacroModelling", "StructuralCausalModels", "MHLib", "IterativeNelderMead", "InteractiveDynamics", "Catlab", "OptimalApplication", "PowerSimulationsDynamics", "ChartParsers", "Dolo", "JavaCall", "Publish", "SumOfSquares", "Luna", "MCPhylo", "ModelingToolkit", "SimplePartitions", "Vega", "TauP", "SourceWalk", "OrbitalTrajectories", "ComoniconGUI", "QuadGK", "RoundAndSwap", "GeneDrive", "Laplacians", "MultivariateFunctions", "Redis", "ElectricGrid", "StLifeIns", "JudiLing", "OceanRobots", "TabularTDLearning", "Gadfly", "JumpProcesses", "FastDifferentiation", "ImageFiltering", "SimpleValueGraphs", "Braket", "BifurcationKit", "GreedyAlign", "MatrixMerge", "NamedArrays", "BeaData", "PowerSystems", "GenomicFeatures", "ExtensibleScheduler", "PowerSimulations", "ParameterizedFunctions", "AlgebraicRewriting", "CompScienceMeshes", "SmallZarrGroups", "Tilde", "SoleModels", "ACTRSimulators", "VegaDatasets", "BitSAD", "MPIMeasurements", "DynamicAxisWarping", "SortingAlgorithms", "GATlab", "SymbolicCodegen", "CharFuncPricing", "MetidaStats", "CUTEst", "ChowLiuTrees", "ITensorNetworks", "KernelDensitySJ", "KiwiConstraintSolver", "Stan", "ImageEdgeDetection", "Symbolics", "PolynomialAmoebas", "Hydrographs", "MatrixNetworks", "SpmImageTycoon", "GlobalSearchRegressionGUI", "BibParser", "ONNXRunTime", "CVRPLIB", "Phonetics", "HybridAStar", "SoleLogics", "LaplacianOpt", "DynamicalSystems", "ForneyLab", "Rimu", "IteratedIntegration", "ImageMorphology", "HydroRefStations", "Polylabel", "QXTools", "QuantumLattices", "GraphNeuralNetworks", "PressureFieldContact", "SigmoidalProgramming", "FindComplexZeros", "CDLmotif", "LFUDACache", "QuantumClifford", "NumCME", "LifeInsuranceDataModel", "SymbolicNumericIntegration", "Causal", "GridWorlds", "CrypticCrosswords", "FoldRNA", "ProjectManagement", "DiffEqJump", "RxInfer", "TuringMachine", "SummarizedExperiments", "MCPhyloTree", "TextModels", "MultiAssayExperiments", "PlateMotionRequests", "Assignment", "Banyan", "Allocations", "OpenStreetMapX", "EchelleBase", "TLDR", "SFrontiers", "MultiAgentPathFinding", "GridGraphs", "SparseDiffTools", "EAGO", "FlagSOS", "TextAnalysis", "RealTimeScheduling", "OnlinePortfolioSelection", "Awabi", "RigidBodySim", "NeXLParticle", "UnfoldCDL", "SortedIteratorProducts", "MathOptInterface", "SimpleGraphs", "ReverseDiffSparse", "Jutul", "TuringCallbacks", "InducingPoints", "PlanarMaps", "FluxTraining", "ReliabilityDiagrams", "Mineos", "StatPlots", "TreesHeaps", "TypeDBClient", "CeMicrodata", "SimpleAiboWebAPI", "ClimaTimeSteppers", "Coulter", "FractionalGaussianFields", "PolynomialRings", "Bonobo", "SoleData", "REDCap", "HerbSearch", "Soss", "ZhuyinPinyin", "CurveFitParameters", "BloqadeQMC", "Empirikos", "ModiaMath", "Agents", "SemanticScholar", "AdaStress", "CMBLensing", "DiscreteMarkovChains", "DiscreteEvents", "MergedIterators", "Shrike", "StochasticDiffEq", "EcologicalNetworks", "NCDatasets", "ReactionNetworkImporters", "GlobalSensitivityAnalysis", "BayesNets", "SolidStateDetectors", "Geomorphometry", "DisplayStructure", "QXZoo", "ExprRules", "NetcdfIO", "EcRequests", "Circo", "Plasmo", "MomentClosure", "Kombinator", "MultivariatePolynomials", "InteractiveChaos", "LightOSM", "Alakazam", "Caesar", "Bangumis", "AccelInterfaces", "Numerics", "Bonsai", "HCubature", "AnytimeWeightedAStar", "Ripserer", "RealNeuralNetworks", "Mill", "YAXArrayBase", "GRIBDatasets", "TermFrequencyInverseDocumentFrequency", "WGPUgfx", "ContextTracking", "ConstraintSolver", "HierarchicalUtils", "SPDX", "VegaLite", "CombinatorialBandits", "Pickle", "ReusableFunctions", "Mads", "ImageSegmentation", "JunctionTrees", "JutulDarcy", "BioMakie", "PolyhedralRelaxations", "SymbolicPlanners", "SweepContractor", "JupyterParameters", "MathTeXEngine", "AssociativeWindowAggregation", "EconoSim", "NextGP", "QuadraticToBinary", "StochasticDelayDiffEq", "StatsModels", "BasicAkerRelationalScore", "Gen", "VectorSphericalWaves", "CurveProximityQueries", "MicrobiomeAnalysis", "SimpleHypergraphs", "ChemometricsData", "OptimizationAlgorithms", "DiffEqCallbacks", "ConcurrentSim", "POMDPStressTesting", "SymbolicUtils", "PDSampler", "RELOG", "ExpandNestedData", "QuantEcon", "VimBindings", "OdsIO", "Dolphyn", "ConstraintTrees", "DickeModel", "COSMO", "Chordal", "BytePairEncoding", "ConstrainedShortestPaths", "OrdinaryDiffEq", "PriorityChannels", "QuantumCitations", "YAXArrays", "MCMCDiagnosticTools", "OmicsProfiles", "SnowyOwl", "PowerApps", "BosonSampling", "DelayDiffEq", "HAML", "ACSets", "Cropbox", "CommonDataModel", "ScatterNNlib", "TexTables", "DrakeVisualizer", "Metatheory", "Erdos", "Dash", "GModelFit", "QueryOperators", "MOTIFs", "GraphMakie", "AlgorithmicCompetition", "ParGOGraphs", "DataFrames", "PyBraket", "SparseExtra", "RBNF", "vOptSpecific", "DiffEqBase", "IncrementalInference", "MemPool", "SmartParser", "RemoteHPC", "CalibrationErrors", "QXContexts", "Starlight", "MIToS", "SimJulia", "PerfectPacking", "Watershed", "Reactive", "PowerSystemCaseBuilder", "CombinatorialEnumeration", "QuickHeaps", "ImplicitGraphs", "ParallelUtilities", "TSPLIB", "LightGraphs", "DynamicBoundspODEsDiscrete", "DoloYAML", "SetProg", "ScHoLP", "Indicomb"])`

**Comment by ericphanson** [comment]
I am a pkg-eval-reader-noob, but I only see 1 failure, which looks like it would be fixed by https://github.com/AdamAker/BasicAkerRelationalScore.jl/pull/3. So this looks pretty good to me.

If there is consensus, we could proceed by:
1. Possibly PR OPFSampler.jl to update it? Not sure if that repo is still active as invenia has folded, and I can't load the package on my m1 laptop
2. PR Datastructures to stop testing the deprecated sort methods for Dict
3. Merge and tag this as a patch release

Perhaps folks can 👍 or 👎 this post to chime in that they agree it is OK to remove the deprecated sort piracy as a bugfix release, given these results. And in a few days if there is agreement we can proceed.

**Comment by maleadt** [comment]
Back to debugging PkgEval (ignore this comment):

@nanosoldier `runtests(configuration = (env=["JULIA_DEBUG=Pkg,loading"],), vs_configuration = (env=["JULIA_DEBUG=Pkg,loading"],))`

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaCollections/OrderedCollections.jl@ff2564b vs. JuliaCollections/OrderedCollections.jl@87a2334: Accepted

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaCollections/OrderedCollections.jl@ff2564b vs. JuliaCollections/OrderedCollections.jl@87a2334: Running

**Comment by oxinabox** [comment]
So i have continued thinking.
(I have been thinking about this since the PR was openned.)
I think we shouldn't do this now.
I am sorry for my very delayed response, and I appreciate that a lot of work has already gone in to validating that there are negligable effects on the package ecosystem.
This package is upstream of like 1/3rd the ecosystem, which means it is upstream of a **ton** of  user scripts and those scripts are not caught by package eval.

I think we should wait either for a major release of OrderedCollections.jl
or at least until we fix deprecations  per https://github.com/JuliaLang/julia/issues/49583 to show deprecations that are your fault during normal exectution. Then we can reassess.

I don't think this is e.g. causing a huge amount of invalidations etc. So I do not see that there is a rush.


It also came up for unrelated releated reasons in a Triage call with @LilithHafner. @JeffBezanson thinks this type piracy is good XD.

**Comment by ericphanson** [comment]
Ok, thanks very much for the feedback! I was actually motivated by Base adding (then reverting) sorting for iterables, which seemed to make this piracy worse to me, since the type you would get would depend on you dependency stack (and whether or not you had Revise loaded, which likely means a difference between the devs machine and prod).

On the other hand, having noisier deprecations first makes a lot of sense too.

**Comment by KristofferC** [comment]
Horrifying.

**Pull request closed without merging**
