### PR TITLE
Drop unneeded lines, otherwise tests fail on Julia 1.6

### PR DESCRIPTION
**Pull request by PallHaraldsson**
Is it correct to drop these lines? And then should also lines 91 and 92 be dropped?

Fixes https://github.com/JuliaCollections/OrderedCollections.jl/issues/62

### CODE REVIEW

**Comment by oxinabox** [comment]
I have  no memory of what these lines were for, and i wrote them...

**Comment by PallHaraldsson** [comment]
I was thinking, maybe for performance reason? They are ambigious in Julia 1.6 why an error here, I didn't think there's a priority mechanism in Julia like in Prolog. Would they simpmply be redundant too in Julia 1.5 (and less) or sometimes be chosen?

I would that for old versions to break. I don't think we need a VERSION check, unless you do...

**Comment by oxinabox** [comment]
Thanks

**Comment by PallHaraldsson** [comment]
I edited old comment to "I wouldn't want for old versions to break." (e.g. 1.5), what I think I meant to write. Did you test somehow or feel confident? And what about lines 91 and 92, just because having them didn't break any tests, I have a feeling they might also break code for Julia 1.6

**Comment by oxinabox** [comment]
> Did you test somehow or feel confident?

I trust two things: and I only need 1 of them to be true
 - If they were important, i would have written tests for them
 - People will open issues rapidly if it broke something. We can revert this PR and tag a new release in 15 minutes.

image

**Comment by PallHaraldsson** [comment]
Ok, I just didn't want to feel responsible for breaking Julia 1.5, it's still important. For me, only I'm more forward-looking and I know with these lines (and possibly the others) Julia 1.6 will(would have) break/broken. I'll try to not worry about the other lines. Just telling you, I'm done looking into Dict batters, at least for now.

**Pull request merged**
