### PR TITLE
LittleDict pop! default

### PR DESCRIPTION
**Pull request by mattBrzezinski**

### CODE REVIEW

**Comment by iamed2** [comment]
I think this could be better implemented as 

```julia
function Base.pop!(dd::UnfrozenLittleDict, key, default=nothing)
    @assert length(dd.keys) == length(dd.vals)
    for ii in 1:length(dd.keys)
        cand = @inbounds dd.keys[ii]
        if isequal(cand, key)
            deleteat!(dd.keys, ii)
            val = @inbounds dd.vals[ii]
            deleteat!(dd.vals, ii)
            return val
        end
    end

    return default
end

**Comment by mattBrzezinski** [comment]
> I think this could be better implemented as
> 
> ```julia
> function Base.pop!(dd::UnfrozenLittleDict, key, default=nothing)
>     @assert length(dd.keys) == length(dd.vals)
>     for ii in 1:length(dd.keys)
>         cand = @inbounds dd.keys[ii]
>         if isequal(cand, key)
>             deleteat!(dd.keys, ii)
>             val = @inbounds dd.vals[ii]
>             deleteat!(dd.vals, ii)
>             return val
>         end
>     end
> 
>     return default
> end
> ```

I can change it to this, I was mainly following the format for [OrderedDict](https://github.com/JuliaCollections/OrderedCollections.jl/blob/5fb23d835c8dd4abd98ba871862426c2e96bafd2/src/ordered_dict.jl#L385) of having a separate function for `(non)-default`.

**Comment by iamed2** [comment]
> I can change it to this, I was mainly following the format for OrderedDict of having a separate function for (non)-default param.

That's actually something to file an issue about; `pop!(::OrderedDict, ::Any)` throws an error when the key isn't found, while `pop!(::UnfrozenLittleDict, ::Any)` returns `nothing`.

**Comment by mattBrzezinski** [comment]
Okay... so I spent a bit of time thinking about this. Turns out I fixed one functionality in #49 but broke another. Whoops.

## Base Dict
- `delete! key`: Returns back the dictionary without the key
- `delete! key DNE`: Returns back the dictionary without the key

- `pop! key`: Returns back the value associated with the key
- `pop! key w/ default`: Returns back the value associated with the key
- `pop! key DNE`: KeyError thrown
- `pop! key DNE w/ default`: Returns back the default value

## Current LittleDict implementation
(I fixed this in #49)
- `delete! key`: Returns back the dictionary without the key
- `delete! key DNE`: Returns back the dictionary without the key

(What I inadvertently didn't realize is this doesn't match)
- `pop! key`: Returns back the value associated with the key
- `pop! key w/ default`: Functionality DNE
- `pop! key DNE`: nothing (this does not match after #49)
- `pop! key DNE w/ default`: Functionality DNE

With these changes `LittleDict` will now match `Dict`. However, I'm not entirely happy with how the solution looks. Any ideas on it @iamed2 ?

**Comment by iamed2** [comment]
Yeah I don't think exceptions should be used for internal control flow here. I think the whole point of the `default` arg is to avoid exceptions entirely. 

One thing you could do is:
```
struct Sentinel end
const sentinel = Sentinel()

function Base.pop!(dd::UnfrozenLittleDict, key, default=sentinel)
    @assert length(dd.keys) == length(dd.vals)
    for ii in 1:length(dd.keys)
        cand = @inbounds dd.keys[ii]
        if isequal(cand, key)
            deleteat!(dd.keys, ii)
            val = @inbounds dd.vals[ii]
            deleteat!(dd.vals, ii)
            return val
        end
    end

    if default === sentinel
        throw(KeyError(key))
    else
        return default
    end
end
```

**Comment by mattBrzezinski** [comment]
> Yeah I don't think exceptions should be used for internal control flow here. I think the whole point of the `default` arg is to avoid exceptions entirely.
> 
> One thing you could do is:
> 
> ```
> struct Sentinel end
> const sentinel = Sentinel()
> 
> function Base.pop!(dd::UnfrozenLittleDict, key, default=sentinel)
>     @assert length(dd.keys) == length(dd.vals)
>     for ii in 1:length(dd.keys)
>         cand = @inbounds dd.keys[ii]
>         if isequal(cand, key)
>             deleteat!(dd.keys, ii)
>             val = @inbounds dd.vals[ii]
>             deleteat!(dd.vals, ii)
>             return val
>         end
>     end
> 
>     if default === sentinel
>         throw(KeyError(key))
>     else
>         return default
>     end
> end
> ```

Only problem with that is if you try and do `delete!(LittleDict(), "foo")`, you'll throw out a `KeyError`. While the `Dict` version will just return back `Dict()`.

**Comment by iamed2** [comment]
> Only problem with that is if you try and do delete!(LittleDict(), "foo"), you'll throw out a KeyError. While the Dict version will just return back Dict().

Then you can pull out this code as an internal method and call it from both:

```julia
struct Sentinel end
const sentinel = Sentinel()

function _pop!(dd::UnfrozenLittleDict, key, default=sentinel)
    @assert length(dd.keys) == length(dd.vals)
    for ii in 1:length(dd.keys)
        cand = @inbounds dd.keys[ii]
        if isequal(cand, key)
            deleteat!(dd.keys, ii)
            val = @inbounds dd.vals[ii]
            deleteat!(dd.vals, ii)
            return val
        end
    end

    return default
end

function Base.pop!(dd::UnfrozenLittleDict, key, default=sentinel)
    val = _pop!(dd, key, default)
    
    if val === sentinel
        throw(KeyError(key))
    else
        return val
    end
end

function Base.delete!(dd::UnfrozenLittleDict, key)
    _pop!(dd, key)
    return dd
end
```

**Pull request closed without merging**
