### PR TITLE
add `thaw` to unfreeze a `LittleDict`

### PR DESCRIPTION
**Pull request by JeffreySarnoff**

### CODE REVIEW

**Comment by oxinabox** [comment]
I am loath to increase the API surface further.
In retrospect adding `freeze` may have been a mistake.
We should have overloaded something in a common namespace (though adding dependencies to OrderedCollections is also not great).
Still too late for that now.

In this particular case we have a method that will `thraw` already.
It is the constructor `LittleDict`:

```julia
julia> using OrderedCollections

julia> frozen = LittleDict((1,2,3), (10,20, 30))
LittleDict{Int64, Int64, Tuple{Int64, Int64, Int64}, Tuple{Int64, Int64, Int64}} with 3 entries:
  1 => 10
  2 => 20
  3 => 30

julia> LittleDict(frozen)
LittleDict{Int64, Int64, Vector{Int64}, Vector{Int64}} with 3 entries:
  1 => 10
  2 => 20
  3 => 30
```

Maybe we could just add a test that that is the behavour, and add it to the docstring for `freeze` ?

**Comment by JeffreySarnoff** [comment]
Adding that to the docs would serve.  I was unaware of it -- I really like LittleDict, and the ability to start frozen, contingently unfreeze to add something, and end frozen is powerful.

**Comment by oxinabox** [comment]
I mostly added freezing as a performance enhancement.
its much faster with tuples than vectors. Or it was

**Comment by JeffreySarnoff** [comment]
still is .. significantly so

**Pull request closed without merging**
